[package]
name = "cursed-timer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfonts = "1.1.0"
chrono = "0.4.22"
crossterm = "0.25.0"
csv = "1.1.6"
rand = "0.8.5"
tui = "0.19.0"
